# Generated by Django 2.2.14 on 2021-03-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platNo', models.CharField(max_length=10)),
                ('jumKursi', models.PositiveIntegerField()),
                ('track1', models.CharField(max_length=15)),
                ('track2', models.CharField(max_length=15)),
                ('img', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
