# Generated by Django 2.2.14 on 2021-03-30 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.CharField(max_length=5)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bus')),
            ],
        ),
    ]
