# Generated by Django 2.2.14 on 2021-03-30 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210330_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='track_akhir',
            field=models.CharField( max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='track_awal',
            field=models.CharField(max_length=15),
            preserve_default=False,
        ),
    ]
