# Generated by Django 2.2.14 on 2021-03-30 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210330_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='track_akhir',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='track_awal',
        ),
        migrations.AddField(
            model_name='bus',
            name='trayek',
            field=models.CharField( max_length=255,null=True,blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='trayek',
            field=models.CharField( max_length=255,null=True,blank=True),
            preserve_default=False,
        ),
    ]
