# Generated by Django 2.2.14 on 2021-03-30 14:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210330_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='bus',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='core.Bus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus',
            name='trayek',
            field=models.CharField( max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='track',
            name='trayek',
            field=models.CharField( max_length=255),
            preserve_default=False,
        ),
    ]
