# Generated by Django 2.2.14 on 2021-03-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210330_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='kursi',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
