# Generated by Django 2.2.14 on 2021-03-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ticket_kursi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='harga',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
