# Generated by Django 2.2.14 on 2021-03-31 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ticket_harga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trayek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='bus',
            name='trayek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Trayek'),
        ),
        migrations.AlterField(
            model_name='track',
            name='trayek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Trayek'),
        ),
    ]
