# Generated by Django 2.2.14 on 2021-03-31 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210331_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='trayek',
            name='trayek',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
